
# html lang
language: en

# main menu navigation
site_brand_name: Frame

menu:
  home: /
  archive: /archives/
  gallery: /categories/gallery/
  about: /about/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/frame.js

# plugin functions
## Mathjax: Math Formula Support
## https://www.mathjax.org
mathjax:
  enable: true
  import: demand # global or demand
  ## global: all pages will load mathjax,this will degrade performance and some grammers may be parsed wrong.
  ## demand: Recommend option,if your post need fomula, you can declare 'mathjax: true' in Front-matter

# favicon
favicon: /favicon.ico

date_format: MMM D, YYYY

# profile
profile:
  title: Frame
  body: Frame is a minimalist, elegant hexo theme.
  image: https://clio-space-1300725494.cos.ap-guangzhou.myqcloud.com/frame/featured_img/profile_cover.png

  links:
    About Frame: /about/
    Blog Tests: /tags/test/
    Gallery View: /categories/gallery/

# footer
footer:
  copyright_info:
    enable: true
    author: © Yonqqi

  powered_by:
    enable: true

  other_info:
    enable: true
    content: Frame is a minimalist, elegant hexo theme.

# color mode
color_mode: classic

