
# html lang
language: en

# header
site_brand_name: Frame.

menu:
  Home: /
  Archive: /archives/
  Gallery: /categories/gallery/
  About: /about/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/frame.js

# favicon
favicon: /favicon.ico

date_format: MMM D, YYYY

# profile
profile:
  title: Hi, this is Frame. 
  body: A minimalist, elegant hexo theme.
  image: /profile_cover.png

  links:
    About Frame: /about/
    Blog Tests: /tags/Test/
    Gallery View: /categories/gallery/

# footer
footer:
  copyright_info:
    enable: true
    author: © Yonqqi

  powered_by: # Powered by Hexo & Frame
    enable: true

  other_info:
    enable: true
    content: Frame is a minimalist, elegant hexo theme.

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: true

